"""core tenancy and dossiers

Revision ID: 0001
Revises:
Create Date: 2026-07-22 17:13:31.166460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', name='user_status'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('token_version > 0', name=op.f('ck_user_sessions_token_version_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    op.create_index('ix_user_sessions_user_revoked_expires', 'user_sessions', ['user_id', 'revoked_at', 'expires_at'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='workspace_status'), server_default='active', nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_workspaces_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_table('decision_subjects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dossier_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='subject_status'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_decision_subjects_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_subjects')),
    sa.UniqueConstraint('workspace_id', 'dossier_id', name='uq_subject_workspace_dossier'),
    sa.UniqueConstraint('workspace_id', 'id', 'dossier_id', name='uq_subject_workspace_id_dossier'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_subject_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'slug', name='uq_subject_workspace_slug')
    )
    op.create_table('domain_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=80), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=160), nullable=False),
    sa.Column('actor', sa.Enum('user', 'system', 'worker', name='domain_event_actor'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_domain_events_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_events')),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_domain_events_workspace_id')
    )
    op.create_index('ix_domain_events_workspace_aggregate_created', 'domain_events', ['workspace_id', 'aggregate_type', 'aggregate_id', 'created_at'], unique=False)
    op.create_table('workspace_memberships',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', name='workspace_role'), nullable=False),
    sa.Column('capabilities', postgresql.ARRAY(sa.Enum('contribute', 'review', 'sign', 'manage_connectors', name='workspace_capability')), server_default=sa.text("'{}'::workspace_capability[]"), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'revoked', name='workspace_membership_status'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_memberships_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_memberships_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_memberships')),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_memberships_workspace_user')
    )
    op.create_index('ix_workspace_memberships_user_status', 'workspace_memberships', ['user_id', 'status'], unique=False)
    op.create_index('ix_workspace_memberships_workspace_status', 'workspace_memberships', ['workspace_id', 'status'], unique=False)
    op.create_table('dossier_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('dossier_id', sa.UUID(), nullable=False),
    sa.Column('decision_subject_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_version', sa.Integer(), nullable=True),
    sa.Column('entry_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('snapshot_hash', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version > 0', name=op.f('ck_dossier_versions_version_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_subject_id', 'dossier_id'], ['decision_subjects.workspace_id', 'decision_subjects.id', 'decision_subjects.dossier_id'], name='fk_dossier_versions_workspace_subject_dossier', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_dossier_versions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dossier_versions')),
    sa.UniqueConstraint('workspace_id', 'dossier_id', 'version', name='uq_dossier_versions_workspace_dossier_version')
    )
    op.create_table('initiatives',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('decision_subject_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='initiative_status'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_subject_id'], ['decision_subjects.workspace_id', 'decision_subjects.id'], name='fk_initiatives_workspace_subject', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_initiatives_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_initiatives')),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_initiative_workspace_id')
    )
    op.create_table('decision_cases',
    sa.Column('decision_case_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('decision_subject_id', sa.UUID(), nullable=False),
    sa.Column('initiative_id', sa.UUID(), nullable=True),
    sa.Column('current_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('decision_question', sa.Text(), nullable=False),
    sa.Column('inferred_decision_type', sa.Enum('market_direction', 'market_entry', 'technology_route', 'resource_allocation', 'unknown', name='decision_type'), server_default='unknown', nullable=False),
    sa.Column('status', sa.Enum('draft', 'scoped', 'ready', 'running', 'review', 'pending_signoff', 'decided', 'monitoring', name='decision_lifecycle_stage'), server_default='draft', nullable=False),
    sa.Column('operational_status', sa.Enum('ok', 'blocked', 'needs_attention', 'cancelled', 'reopened', 'archived', name='case_operational_status'), server_default='ok', nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('five_w_one_h', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('goals', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('stakeholders', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('selected_dossier_entry_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('case_entry_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('assumption_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('option_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('charter_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('analysis_run_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('report_artifact_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('causal_graph_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('current_decision_record_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_version > 0', name=op.f('ck_decision_cases_current_version_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_subject_id'], ['decision_subjects.workspace_id', 'decision_subjects.id'], name='fk_decision_cases_workspace_subject', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'initiative_id'], ['initiatives.workspace_id', 'initiatives.id'], name='fk_decision_cases_workspace_initiative', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_decision_cases_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('decision_case_id', name=op.f('pk_decision_cases')),
    sa.UniqueConstraint('workspace_id', 'decision_case_id', name='uq_decision_cases_workspace_id')
    )
    op.create_index('ix_decision_cases_workspace_status_updated', 'decision_cases', ['workspace_id', 'status', 'updated_at'], unique=False)
    op.create_table('candidate_revisions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('decision_case_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.Enum('conversation', 'analysis', 'simulation', name='candidate_source_type'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('base_dossier_version', sa.Integer(), nullable=False),
    sa.Column('base_case_version', sa.Integer(), nullable=True),
    sa.Column('proposals', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.Enum('pending', 'partially_accepted', 'accepted', 'rejected', name='candidate_revision_status'), server_default='pending', nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('base_dossier_version > 0', name=op.f('ck_candidate_revisions_base_dossier_version_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_case_id'], ['decision_cases.workspace_id', 'decision_cases.decision_case_id'], name='fk_candidate_revisions_workspace_case', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_candidate_revisions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_revisions')),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_candidate_revisions_workspace_id')
    )
    op.create_index('ix_candidate_revisions_workspace_status', 'candidate_revisions', ['workspace_id', 'status'], unique=False)
    op.create_table('case_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('decision_case_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_version', sa.Integer(), nullable=True),
    sa.Column('dossier_version', sa.Integer(), nullable=False),
    sa.Column('dossier_snapshot_hash', sa.Text(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snapshot_hash', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version > 0', name=op.f('ck_case_versions_version_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_case_id'], ['decision_cases.workspace_id', 'decision_cases.decision_case_id'], name='fk_case_versions_workspace_case', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_case_versions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_versions')),
    sa.UniqueConstraint('workspace_id', 'decision_case_id', 'version', name='uq_case_versions_workspace_case_version')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('decision_subject_id', sa.UUID(), nullable=True),
    sa.Column('decision_case_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('decision_case_id IS NULL OR decision_subject_id IS NOT NULL', name=op.f('ck_conversations_case_requires_subject')),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_case_id'], ['decision_cases.workspace_id', 'decision_cases.decision_case_id'], name='fk_conversations_workspace_case', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_subject_id'], ['decision_subjects.workspace_id', 'decision_subjects.id'], name='fk_conversations_workspace_subject', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_conversations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_conversations_workspace_id')
    )
    op.create_table('dossier_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('decision_subject_id', sa.UUID(), nullable=False),
    sa.Column('decision_case_id', sa.UUID(), nullable=True),
    sa.Column('scope', sa.Enum('subject', 'case', name='dossier_scope'), nullable=False),
    sa.Column('statement_type', sa.Enum('fact', 'evidence', 'assumption', 'judgment', 'preference', 'unknown', 'constraint', name='dossier_statement_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('candidate', 'confirmed', 'rejected', 'expired', 'conflicted', name='entry_status'), server_default='candidate', nullable=False),
    sa.Column('source_type', sa.Enum('user', 'ai_candidate', 'evidence', 'analysis_candidate', 'simulation_candidate', name='dossier_source_type'), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint("(scope = 'subject' AND decision_case_id IS NULL) OR (scope = 'case' AND decision_case_id IS NOT NULL)", name=op.f('ck_dossier_entries_scope_matches_case')),
    sa.CheckConstraint('version > 0', name=op.f('ck_dossier_entries_version_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_case_id'], ['decision_cases.workspace_id', 'decision_cases.decision_case_id'], name='fk_dossier_entries_workspace_case', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_subject_id'], ['decision_subjects.workspace_id', 'decision_subjects.id'], name='fk_dossier_entries_workspace_subject', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_dossier_entries_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dossier_entries')),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_dossier_entries_workspace_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('decision_subject_id', sa.UUID(), nullable=True),
    sa.Column('decision_case_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('request_model_id', sa.String(length=160), nullable=True),
    sa.Column('response_model_id', sa.String(length=160), nullable=True),
    sa.Column('provider_response_version', sa.String(length=160), nullable=True),
    sa.Column('token_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('cost_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'conversation_id'], ['conversations.workspace_id', 'conversations.id'], name='fk_messages_workspace_conversation', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_case_id'], ['decision_cases.workspace_id', 'decision_cases.decision_case_id'], name='fk_messages_workspace_case', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_subject_id'], ['decision_subjects.workspace_id', 'decision_subjects.id'], name='fk_messages_workspace_subject', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_messages_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_messages_workspace_id')
    )
    op.create_index('ix_messages_workspace_conversation_created', 'messages', ['workspace_id', 'conversation_id', 'created_at'], unique=False)
    op.create_table('quick_analysis_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('decision_case_id', sa.UUID(), nullable=True),
    sa.Column('formality', sa.Enum('non_formal', name='quick_analysis_formality'), server_default='non_formal', nullable=False),
    sa.Column('judgment', sa.Text(), nullable=False),
    sa.Column('counter_arguments', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('key_unknowns', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('next_actions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'conversation_id'], ['conversations.workspace_id', 'conversations.id'], name='fk_quick_analysis_workspace_conversation', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_case_id'], ['decision_cases.workspace_id', 'decision_cases.decision_case_id'], name='fk_quick_analysis_workspace_case', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_quick_analysis_results_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quick_analysis_results')),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_quick_analysis_results_workspace_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quick_analysis_results')
    op.drop_index('ix_messages_workspace_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_table('dossier_entries')
    op.drop_table('conversations')
    op.drop_table('case_versions')
    op.drop_index('ix_candidate_revisions_workspace_status', table_name='candidate_revisions')
    op.drop_table('candidate_revisions')
    op.drop_index('ix_decision_cases_workspace_status_updated', table_name='decision_cases')
    op.drop_table('decision_cases')
    op.drop_table('initiatives')
    op.drop_table('dossier_versions')
    op.drop_index('ix_workspace_memberships_workspace_status', table_name='workspace_memberships')
    op.drop_index('ix_workspace_memberships_user_status', table_name='workspace_memberships')
    op.drop_table('workspace_memberships')
    op.drop_index('ix_domain_events_workspace_aggregate_created', table_name='domain_events')
    op.drop_table('domain_events')
    op.drop_table('decision_subjects')
    op.drop_table('workspaces')
    op.drop_index('ix_user_sessions_user_revoked_expires', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('users')
    # ### end Alembic commands ###

    bind = op.get_bind()
    enum_names = (
        'quick_analysis_formality',
        'message_role',
        'dossier_scope',
        'dossier_source_type',
        'dossier_statement_type',
        'entry_status',
        'candidate_revision_status',
        'candidate_source_type',
        'case_operational_status',
        'decision_lifecycle_stage',
        'decision_type',
        'initiative_status',
        'workspace_membership_status',
        'workspace_capability',
        'workspace_role',
        'domain_event_actor',
        'subject_status',
        'workspace_status',
        'user_status',
    )
    for enum_name in enum_names:
        postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
