"""align evidence_funnel_audits/retrieval_coverage types and workspace FKs with models

Revision ID: 2b4f48b5afea
Revises: a9f1e2d3c4b5
Create Date: 2026-08-05 10:16:55.849280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2b4f48b5afea'
down_revision: Union[str, Sequence[str], None] = 'a9f1e2d3c4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evidence_funnel_audits', 'low_tier_share',
               existing_type=sa.NUMERIC(precision=6, scale=3),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_foreign_key(op.f('fk_evidence_funnel_audits_workspace_id_workspaces'), 'evidence_funnel_audits', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # The varchar default cannot be auto-cast onto the new enum type, so it is
    # dropped before the type switch and re-created in the enum form after.
    op.alter_column('retrieval_coverage', 'origin_mode',
               existing_type=sa.VARCHAR(length=16),
               server_default=None)
    op.alter_column('retrieval_coverage', 'origin_mode',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('live', 'cached', 'fixture', name='origin_mode'),
               existing_nullable=False,
               postgresql_using="origin_mode::origin_mode")
    op.alter_column('retrieval_coverage', 'origin_mode',
               existing_type=sa.Enum('live', 'cached', 'fixture', name='origin_mode'),
               server_default=sa.text("'live'::origin_mode"))
    op.create_foreign_key(op.f('fk_retrieval_coverage_workspace_id_workspaces'), 'retrieval_coverage', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_retrieval_coverage_workspace_id_workspaces'), 'retrieval_coverage', type_='foreignkey')
    op.alter_column('retrieval_coverage', 'origin_mode',
               existing_type=sa.Enum('live', 'cached', 'fixture', name='origin_mode'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'live'::character varying"))
    op.drop_constraint(op.f('fk_evidence_funnel_audits_workspace_id_workspaces'), 'evidence_funnel_audits', type_='foreignkey')
    op.alter_column('evidence_funnel_audits', 'low_tier_share',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=6, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###
