"""add canonical contract foundations

Revision ID: 6b246c283d7a
Revises: 0001
Create Date: 2026-07-23 18:21:00.137266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6b246c283d7a'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('analysis_run_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('decision_case_id', sa.UUID(), nullable=False),
    sa.Column('charter_id', sa.UUID(), nullable=False),
    sa.Column('charter_version', sa.Integer(), nullable=False),
    sa.Column('run_manifest_id', sa.UUID(), nullable=False),
    sa.Column('run_manifest_hash', sa.String(length=256), nullable=False),
    sa.Column('cynefin_gate_result_id', sa.UUID(), nullable=False),
    sa.Column('analysis_level', sa.Enum('focused', 'full', name='formal_analysis_level'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'planning', 'retrieving', 'analyzing', 'criticizing', 'synthesizing', 'validating', 'ready', 'blocked', 'needs_attention', 'cancelled', name='analysis_run_status'), server_default='queued', nullable=False),
    sa.Column('progress', sa.Float(), server_default='0', nullable=False),
    sa.Column('origin_modes', postgresql.ARRAY(sa.Enum('live', 'cached', 'fixture', name='origin_mode')), server_default=sa.text("'{}'::origin_mode[]"), nullable=False),
    sa.Column('case_version', sa.Integer(), nullable=False),
    sa.Column('case_snapshot_hash', sa.String(length=256), nullable=False),
    sa.Column('dossier_snapshot_version', sa.Integer(), nullable=False),
    sa.Column('dossier_snapshot_hash', sa.String(length=256), nullable=False),
    sa.Column('method_id', sa.String(length=160), nullable=False),
    sa.Column('method_version', sa.String(length=64), nullable=False),
    sa.Column('method_content_hash', sa.String(length=256), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default='1', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='1', nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage_results', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('strategic_lens_artifact_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('last_resumable_stage', sa.Enum('queued', 'planning', 'retrieving', 'analyzing', 'criticizing', 'synthesizing', 'validating', 'ready', 'blocked', 'needs_attention', 'cancelled', name='analysis_run_status'), nullable=True),
    sa.Column('interruption_classification_id', sa.UUID(), nullable=True),
    sa.Column('supersedes_analysis_run_id', sa.UUID(), nullable=True),
    sa.Column('superseded_by_analysis_run_id', sa.UUID(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('attempt <= max_attempts', name=op.f('ck_analysis_runs_attempt_within_max')),
    sa.CheckConstraint('attempt > 0', name=op.f('ck_analysis_runs_attempt_positive')),
    sa.CheckConstraint('case_version > 0', name=op.f('ck_analysis_runs_case_version_positive')),
    sa.CheckConstraint('charter_version > 0', name=op.f('ck_analysis_runs_charter_version_positive')),
    sa.CheckConstraint('dossier_snapshot_version > 0', name=op.f('ck_analysis_runs_dossier_snapshot_version_positive')),
    sa.CheckConstraint('max_attempts > 0', name=op.f('ck_analysis_runs_max_attempts_positive')),
    sa.CheckConstraint("last_resumable_stage IS NULL OR last_resumable_stage IN ('planning', 'retrieving', 'analyzing', 'criticizing', 'synthesizing', 'validating')", name=op.f('ck_analysis_runs_last_resumable_stage_valid')),
    sa.CheckConstraint('progress >= 0 AND progress <= 1', name=op.f('ck_analysis_runs_progress_range')),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_case_id'], ['decision_cases.workspace_id', 'decision_cases.decision_case_id'], name='fk_analysis_runs_workspace_case', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'superseded_by_analysis_run_id'], ['analysis_runs.workspace_id', 'analysis_runs.analysis_run_id'], name='fk_analysis_runs_workspace_superseded_by', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'supersedes_analysis_run_id'], ['analysis_runs.workspace_id', 'analysis_runs.analysis_run_id'], name='fk_analysis_runs_workspace_supersedes', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_analysis_runs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_run_id', name=op.f('pk_analysis_runs')),
    sa.UniqueConstraint('workspace_id', 'analysis_run_id', name='uq_analysis_runs_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'decision_case_id', 'analysis_run_id', name='uq_analysis_runs_workspace_case_id'),
    sa.UniqueConstraint('workspace_id', 'idempotency_key', name='uq_analysis_runs_workspace_idempotency')
    )
    op.create_index('ix_analysis_runs_workspace_case_status', 'analysis_runs', ['workspace_id', 'decision_case_id', 'status'], unique=False)
    op.create_table('signoff_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('decision_case_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_hash', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('pending', 'signed', 'declined', 'cancelled', 'expired', name='signoff_request_status'), server_default='pending', nullable=False),
    sa.Column('nonce_hash', sa.String(length=256), nullable=False),
    sa.Column('nonce_issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status <> 'signed' OR signed_at IS NOT NULL", name=op.f('ck_signoff_requests_signed_has_timestamp')),
    sa.CheckConstraint('expires_at > nonce_issued_at', name=op.f('ck_signoff_requests_expiry_after_nonce')),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_signoff_requests_requested_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_case_id'], ['decision_cases.workspace_id', 'decision_cases.decision_case_id'], name='fk_signoff_requests_workspace_case', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_signoff_requests_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signoff_requests')),
    sa.UniqueConstraint('workspace_id', 'decision_case_id', 'id', name='uq_signoff_requests_workspace_case_id'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_signoff_requests_workspace_id')
    )
    op.create_index('ix_signoff_requests_workspace_case_status', 'signoff_requests', ['workspace_id', 'decision_case_id', 'status'], unique=False)
    op.create_table('simulation_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('decision_case_id', sa.UUID(), nullable=False),
    sa.Column('graph_id', sa.UUID(), nullable=False),
    sa.Column('graph_version_id', sa.UUID(), nullable=False),
    sa.Column('strategy_version_id', sa.UUID(), nullable=False),
    sa.Column('scenario_version_id', sa.UUID(), nullable=False),
    sa.Column('score_definition_id', sa.UUID(), nullable=False),
    sa.Column('score_definition_version', sa.String(length=80), nullable=False),
    sa.Column('decision_maker_profile_id', sa.UUID(), nullable=False),
    sa.Column('decision_maker_profile_version', sa.Integer(), nullable=False),
    sa.Column('risk_tolerance', sa.Float(), nullable=False),
    sa.Column('engine_version', sa.String(length=80), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('simulation_mode', sa.Enum('formal', 'experimental', name='simulation_mode'), nullable=False),
    sa.Column('epsilon', sa.Float(), nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('input_hash', sa.String(length=256), nullable=False),
    sa.Column('node_results', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('option_scores', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('top_drivers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('recommendation_shift', sa.Text(), nullable=False),
    sa.Column('convergence_status', sa.Enum('converged', 'max_steps', 'saturated', 'invalid', name='simulation_convergence_status'), nullable=False),
    sa.Column('origin_modes', postgresql.ARRAY(sa.Enum('live', 'cached', 'fixture', name='origin_mode')), server_default=sa.text("'{}'::origin_mode[]"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('decision_maker_profile_version > 0', name=op.f('ck_simulation_runs_profile_version_positive')),
    sa.CheckConstraint('epsilon > 0', name=op.f('ck_simulation_runs_epsilon_positive')),
    sa.CheckConstraint('max_steps > 0', name=op.f('ck_simulation_runs_max_steps_positive')),
    sa.CheckConstraint('risk_tolerance >= 0 AND risk_tolerance <= 1', name=op.f('ck_simulation_runs_risk_tolerance_range')),
    sa.CheckConstraint('steps >= 0 AND steps <= max_steps', name=op.f('ck_simulation_runs_steps_range')),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_case_id'], ['decision_cases.workspace_id', 'decision_cases.decision_case_id'], name='fk_simulation_runs_workspace_case', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_simulation_runs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulation_runs')),
    sa.UniqueConstraint('workspace_id', 'decision_case_id', 'id', name='uq_simulation_runs_workspace_case_id'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_simulation_runs_workspace_id')
    )
    op.create_index('ix_simulation_runs_workspace_case_created', 'simulation_runs', ['workspace_id', 'decision_case_id', 'created_at'], unique=False)
    op.create_index('ix_simulation_runs_workspace_input_hash', 'simulation_runs', ['workspace_id', 'input_hash'], unique=False)
    op.create_table('source_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('decision_case_id', sa.UUID(), nullable=False),
    sa.Column('source_scope', sa.Enum('pre_run', 'run_frozen', name='source_scope'), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=True),
    sa.Column('frozen_from_source_record_id', sa.UUID(), nullable=True),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kind', sa.Enum('web_page', 'provider_result', 'uploaded_file', 'human_input', 'case_snapshot', name='source_kind'), nullable=False),
    sa.Column('canonical_uri', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content_hash', sa.String(length=256), nullable=False),
    sa.Column('source_version', sa.String(length=160), nullable=False),
    sa.Column('origin_mode', sa.Enum('live', 'cached', 'fixture', name='origin_mode'), nullable=False),
    sa.Column('raw_artifact_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(source_scope = 'pre_run' AND analysis_run_id IS NULL AND frozen_from_source_record_id IS NULL AND frozen_at IS NULL) OR (source_scope = 'run_frozen' AND analysis_run_id IS NOT NULL AND frozen_from_source_record_id IS NOT NULL AND frozen_at IS NOT NULL)", name=op.f('ck_source_records_source_scope_fields_consistent')),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_case_id', 'analysis_run_id'], ['analysis_runs.workspace_id', 'analysis_runs.decision_case_id', 'analysis_runs.analysis_run_id'], name='fk_source_records_workspace_case_run', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_case_id', 'frozen_from_source_record_id'], ['source_records.workspace_id', 'source_records.decision_case_id', 'source_records.id'], name='fk_source_records_workspace_case_frozen_from', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_case_id'], ['decision_cases.workspace_id', 'decision_cases.decision_case_id'], name='fk_source_records_workspace_case', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_source_records_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_records')),
    sa.UniqueConstraint('workspace_id', 'decision_case_id', 'id', name='uq_source_records_workspace_case_id'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_source_records_workspace_id')
    )
    op.create_index('ix_source_records_workspace_case_scope', 'source_records', ['workspace_id', 'decision_case_id', 'source_scope'], unique=False)
    op.create_table('source_spans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('decision_case_id', sa.UUID(), nullable=False),
    sa.Column('source_record_id', sa.UUID(), nullable=False),
    sa.Column('source_scope', sa.Enum('pre_run', 'run_frozen', name='source_scope'), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=True),
    sa.Column('frozen_from_source_span_id', sa.UUID(), nullable=True),
    sa.Column('locator', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('quote_hash', sa.String(length=256), nullable=False),
    sa.Column('context_before', sa.Text(), nullable=True),
    sa.Column('context_after', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(source_scope = 'pre_run' AND analysis_run_id IS NULL AND frozen_from_source_span_id IS NULL) OR (source_scope = 'run_frozen' AND analysis_run_id IS NOT NULL AND frozen_from_source_span_id IS NOT NULL)", name=op.f('ck_source_spans_source_scope_fields_consistent')),
    sa.CheckConstraint("locator <> '{}'::jsonb", name=op.f('ck_source_spans_locator_not_empty')),
    sa.CheckConstraint('length(quote) > 0', name=op.f('ck_source_spans_quote_not_empty')),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_case_id', 'analysis_run_id'], ['analysis_runs.workspace_id', 'analysis_runs.decision_case_id', 'analysis_runs.analysis_run_id'], name='fk_source_spans_workspace_case_run', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_case_id', 'frozen_from_source_span_id'], ['source_spans.workspace_id', 'source_spans.decision_case_id', 'source_spans.id'], name='fk_source_spans_workspace_case_frozen_from', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_case_id', 'source_record_id'], ['source_records.workspace_id', 'source_records.decision_case_id', 'source_records.id'], name='fk_source_spans_workspace_case_source', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'decision_case_id'], ['decision_cases.workspace_id', 'decision_cases.decision_case_id'], name='fk_source_spans_workspace_case', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_source_spans_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_spans')),
    sa.UniqueConstraint('workspace_id', 'decision_case_id', 'id', name='uq_source_spans_workspace_case_id'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_source_spans_workspace_id')
    )
    op.create_index('ix_source_spans_workspace_case_scope', 'source_spans', ['workspace_id', 'decision_case_id', 'source_scope'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_spans_workspace_case_scope', table_name='source_spans')
    op.drop_table('source_spans')
    op.drop_index('ix_source_records_workspace_case_scope', table_name='source_records')
    op.drop_table('source_records')
    op.drop_index('ix_simulation_runs_workspace_input_hash', table_name='simulation_runs')
    op.drop_index('ix_simulation_runs_workspace_case_created', table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_index('ix_signoff_requests_workspace_case_status', table_name='signoff_requests')
    op.drop_table('signoff_requests')
    op.drop_index('ix_analysis_runs_workspace_case_status', table_name='analysis_runs')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###

    bind = op.get_bind()
    enum_names = (
        'source_scope',
        'source_kind',
        'simulation_convergence_status',
        'simulation_mode',
        'signoff_request_status',
        'origin_mode',
        'analysis_run_status',
        'formal_analysis_level',
    )
    for enum_name in enum_names:
        postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
