"""harden canonical contract invariants

Revision ID: f850d361ee42
Revises: 6b246c283d7a
Create Date: 2026-07-23 20:34:20.195194

"""
from typing import Sequence, Union

from alembic import op


revision: str = 'f850d361ee42'
down_revision: Union[str, Sequence[str], None] = '6b246c283d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_analysis_runs_workspace_superseded_by'), 'analysis_runs', type_='foreignkey')
    op.drop_constraint(op.f('fk_analysis_runs_workspace_supersedes'), 'analysis_runs', type_='foreignkey')
    op.create_foreign_key('fk_analysis_runs_workspace_superseded_by', 'analysis_runs', 'analysis_runs', ['workspace_id', 'decision_case_id', 'superseded_by_analysis_run_id'], ['workspace_id', 'decision_case_id', 'analysis_run_id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_analysis_runs_workspace_supersedes', 'analysis_runs', 'analysis_runs', ['workspace_id', 'decision_case_id', 'supersedes_analysis_run_id'], ['workspace_id', 'decision_case_id', 'analysis_run_id'], ondelete='RESTRICT')
    op.create_check_constraint(
        op.f('ck_source_records_raw_artifact_matches_source_kind'),
        'source_records',
        "kind NOT IN ('human_input', 'case_snapshot') OR raw_artifact_id IS NULL",
    )
    op.drop_constraint(
        op.f('ck_simulation_runs_epsilon_positive'),
        'simulation_runs',
        type_='check',
    )
    op.create_check_constraint(
        op.f('ck_simulation_runs_epsilon_finite_positive'),
        'simulation_runs',
        "epsilon > 0 AND epsilon < 'Infinity'::double precision",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('ck_simulation_runs_epsilon_finite_positive'),
        'simulation_runs',
        type_='check',
    )
    op.create_check_constraint(
        op.f('ck_simulation_runs_epsilon_positive'),
        'simulation_runs',
        'epsilon > 0',
    )
    op.drop_constraint(
        op.f('ck_source_records_raw_artifact_matches_source_kind'),
        'source_records',
        type_='check',
    )
    op.drop_constraint('fk_analysis_runs_workspace_supersedes', 'analysis_runs', type_='foreignkey')
    op.drop_constraint('fk_analysis_runs_workspace_superseded_by', 'analysis_runs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_analysis_runs_workspace_supersedes'), 'analysis_runs', 'analysis_runs', ['workspace_id', 'supersedes_analysis_run_id'], ['workspace_id', 'analysis_run_id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_analysis_runs_workspace_superseded_by'), 'analysis_runs', 'analysis_runs', ['workspace_id', 'superseded_by_analysis_run_id'], ['workspace_id', 'analysis_run_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
